name: CI

on: 
  push: 
    branches: [master]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps: 
      - uses: actions/checkout@v2
      - name: debian-install 
        run: sudo make install　OS=Debian

      - name: debian-link
        run: sudo make link OS=Debian

      - name: unlink
        run: sudo make unlink
